sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

cache:
    pip: true
    ccache: true
    directories:
     - /home/travis/.conan/
before_install:
    - sudo apt-get update -y

install:
    - sudo apt-get install cmake3; alias cmake='cmake3' || true
    - sudo apt-get install -y libsnappy1 libsnappy-dev libgoogle-glog-dev
    - sudo apt-get install -y libgflags-dev libgflags2
    - sudo apt-get install -y openjdk-7-jdk openjdk-7-jre
    - sudo apt-get install -y libprotobuf-dev libprotobuf8 protobuf-compiler
    - sudo apt-get install -y libhiredis-dev libhiredis0.10
    - sudo apt-get install -y libgtest-dev
    - sudo apt-get install -y libevent-2.0-5 libevent-dev
    - sudo apt-get install -y thrift-compiler
    - sudo apt-get install -y liblog4cpp5 liblog4cpp5-dev
    - sudo apt-get install -y libgoogle-glog0 libgoogle-glog-dev
    - sudo pip install conan || true
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan || true
    - sudo conan install . --build=missing
script:
    - source build_by_conan.sh; cmake . ; make -j


after_success:
    -



