sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

cache:
    pip: true
    ccache: true
    directories:
     - /home/travis/.conan/
before_install:
    - sudo apt-get update -y

install:
    - sudo apt-get install cmake3; alias cmake='cmake3' || true
    - sudo pip install conan || true
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan || true
    - sudo conan install . --build=missing
script:
    - sh build_by_conan.sh


after_success:
    -



